apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUlJmTHZZa2p1Nm93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMU1qY3hNREF3TXpkYUZ3MHpOVEExTWpVeE1EQTFNemRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN5ZVpaKzdIYkFzR1dvbnZrbUIydVF4d3BQeEVzY0V1ME9RQ0ViN09QSWlyeFVaQUwxRzdhWXowNm0KUGI5eHVlb05ObGZNalM2b25nU21YWU1jNFI4YlVDaVBlYmlsYTVRT0p1S3FzZlBGZ2RNdFZXV29RbnZkbGoyYQpsWXRHTnZ3Z1pUaVhOaEE5NHJHbmlOaFlsV1pTZGhCbnh4RGJsM2djY2xteXZpUVlEWXFuYXJCV0xiK25XWHA5CityK2gwQXd0WlNFSW9Zb3lQVzFYOEdUcWRRNG1DWkRUcDRMaDdCQWdLaGtKemY1VGphcDd5bGpSY0tKT1FmMGkKK1RGc3dsK04yMXRORXltd3BvSWo4NjlpT1JBYTdlMkNFSU9qanNPQ29teWhIeTcvRlZDajNZNUJteFV4bXRtbApOL21zSnN5VSt2R2dkL2k5MkdGME9zdDJBV2ZuQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQ3k4ZlU0YmdraFVOaFFKTGJWbUFocWJFWnREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWVMS1l6Yk1QOAplSXdVSUg5ckcxeXFxbU0zb0dOd0xqeGpPenYybzhXSzQ4NkQ2ekZWcVlCZGtMbm4veCs0bVJtVDZEaWNpODlnCmx3QzdsRWprT3RsVzFpVllsblFaYUlibFFGQy9nRGJIYStqb2d2d2ZIRjFyREh2bzh4WGtobnpXV0NqTmtLY2wKNUhZaWRIK24wRzB0UmFKa0dUelNQOVpSeWFOcmtlaHc5TTlONWZLWUF3Nk9QbXVvVDlDbWpGOWpwbjVLUFBUSAorcXc5VFRzRkdTY0hLQzdBVTluZnVwRmF1KzdwLzVzVU5GOVh0bk04NzRYeGFBSWxPeEhGQUlOVDdsc2lqem9FCm1HbnpTc3cwVW5qNjZBbG9pS211V250ZVZvTXJjSG1UQnVhUlBDK3VxSHJiUmpNc0xCNktvS2NyWEhjV2xBbWgKN1dGMGwraEd6WXBWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://B27333BFCD805E63A67C70D64643E3B9.sk1.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:489994096722:cluster/default-Ahmad-EKS
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYmlJNGFZUEdIQkF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMk1ESXhNREV3TlRCYUZ3MHpOVEExTXpFeE1ERTFOVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPcGY5OUlFS0IvYkNiMWN4eVBYRGVvOFlTN2IwYUR3c0dJMVVNL2NLZVhsOWwrbjN3SEpDMmVGVUMKOGlXQXF3QlVVWi9VOTFoc255Z1c4SUJ1Y1pZaGZwQzhWY0VjM2RmQ2doY0pWZTczc1lJLzlZNEVrUW1lODZaVQp0bWdMcE84ekdYR01jUE9UL2JuQ1JqRzZsS0Z3WnpxOXRyV0l1ZFBrMlZIdEV3K1BSUnE5MGxqQytmZm84OVVlCjQ3UFJsbkk1SzVKWThGODg3Uk5Jdjl4a3RkZExnVkw0U0dlNittVlhxUVRXVEViQmlKb1czUXdkekVJR1Y3UGgKbU1JS1VoenZvaDlvK2R1eEowOUJmbVZDdXZQSE0zMGZjMGtDNFJEU2l2ZEoxK0pvYmVva0VFdk5sVGpCTGNQQgp3U3pTSThrQnRtL3N6Z055N2VSeEpFZG4rRTF0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJROUlIS2U3cFlmWnpZeDVhbnlKUXNJNjQwaTJEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2g5SE12U1lQTApaSWkrNStRNW9tNnllQW1oQlZ0d0JFNHQ4Q0ltTU1RYXZEb0FvTzV1dkxvYVZFWVluRzhzMjByT2Q0VDh5cUdTClZCck54VXRlaDBwT2JqNnF3MHB6T1hvNlZaNDNwNW50Y0NUNko2eitmcEFxZDdka3JldDl5SkgyK1pkc1gwclgKSCs2cVlLL0syR1RxZy9veElKQ041M1pYdmQ1ekNRalhsbTUrdEE0L1FSTDFQZXloeFgrK0pDczJXZ2Q5SEYxawpzdm9LZmNUYTBVK2xxM0tmdG5vMkJvMTEyR085aExCZzJmWVVLZFFPcm1taGFvRWQ5Zk13QXpmSlE0bmxNRjZWCm4xYWJOemNLZ2ozaEZBRjhDZ29wRmxPOXRzakRwbXNrYlVoM2xnc2dFSkZ0ZmltUTAwUVpFZjAxSnF6NHdKSVMKK2FydlBUMXBaZ0lvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://D3C2CFE65944E4019834D741EA3B6C57.gr7.us-west-1.eks.amazonaws.com
  name: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:489994096722:cluster/default-Ahmad-EKS
    user: arn:aws:eks:us-east-1:489994096722:cluster/default-Ahmad-EKS
  name: arn:aws:eks:us-east-1:489994096722:cluster/default-Ahmad-EKS
- context:
    cluster: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
    user: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
  name: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
current-context: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:489994096722:cluster/default-Ahmad-EKS
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - default-Ahmad-EKS
      command: aws
- name: arn:aws:eks:us-west-1:489994096722:cluster/Saad-Eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - Saad-Eks
      command: aws
