apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: app

spec:
  provider: aws
  parameters:
    objects: |
      - objectName: testing
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: ctf_username
          - path: password
            objectAlias: ctf_password

  secretObjects:
  - secretName: ctf-credentials
    type: Opaque
    data:
    - key: username
      objectName: ctf_username

    - key: password
      objectName: ctf_password

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::680688655542:role/eks-node-group-Ahmad
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: app
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: ctf-credentials
          key: username
    # envFrom:
    # - secretRef:
    #     name: ctf-credentials
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets"