name: 'Configure kubectl'
description: 'Set up and configure kubectl with a service account token'
inputs:
  K8S_SERVICE_ACCOUNT_TOKEN:
    description: 'Service account token for Kubernetes'
    required: true
  KUBERNETES_SERVER:
    description: 'Kubernetes API server URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Configure kubectl with service account token
      shell: bash
      run: |
        kubectl config set-cluster my-cluster --server=${{ inputs.KUBERNETES_SERVER }}
        kubectl config set-credentials github-actions-sa --token=${{ inputs.K8S_SERVICE_ACCOUNT_TOKEN }}
        kubectl config set-context my-context --cluster=my-cluster --user=github-actions-sa
        kubectl config use-context my-context
        kubectl get pod
