apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZVVyTTFLVHNrNll3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01qUXhOVE01TWpWYUZ3MHpOVEV3TWpJeE5UUTBNalZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCRk5XajdTYmQxakxEdnRsWEhRcjVWN0lkV3hzNWJLNG5XekVjRWNNelFGUjIxSEZSSkYrdHBCbS8KTlN4b1FYbHZpQmI0eFhGRlB0MFhBQTQ4QWJ3WXdsN0ZmR2VXemJteHBZT0tuWHF3VUY2dDNPOW02a3dMWnpkRwpabnc0cTM0YUpyQ08zWm41Myt3d1Y3NGJYaE5tZmZOam5GZUw0VVFVVk5DM0VBYlh4UVNpOSttQVBVcmZCNEdYCmQ0VTNhNnhybGgvQVA0cnlrNnhkMEFWMmNmRzZ4Qy9Ldlk1bzB2YWdlOTJSN3VERTFFSnlVZmZGaG9YNGg5YUcKRkJpMXRiSzNUM09wYVlENkxDeG5mUGlSVTBoQy9RQ3l3TjdxeE5PLzRBN1JCZVJTbHJQWGQxa3BkTjBvMStnZwozc04yVDAxeVYvYjNMaW40Nit0S20zUnhzcmdKQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUOTFGQjIvbWM1cWo1eTNFbjIwL0c3dTdHY3hqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmVEZ2hNWDdXMwozOW1FRkxrTDZwL1dBc1dXMVlPQnFvcnNaUTFpbVFYRm9TOElHTmhweGYxWDRaMEsxUzJISGNxUzliRytBYTJBCnp4a0dXd3NIUFRyZ3JLUllaUUsyQ3VzczVGdy95TTZqdWxkaWtvYmdQbSszN2pRYmEyMTJCZENxK3BQNEZWVDgKODNRdVllalFmNUY2WjVTN285RGY1bm85VDJTcU5TRTVqYzByd3JaaXNsemk4Sis2aXdvQ0ZxWmhhYVVXZjhMRQpPdVpUR3ZFU3lHd2kyTGFCd2p4Z1IrbCtvalVpdng3aVlQSGRCb1UxTEtLVnNaNXI3THUzaFVPWm1oTVlIZ2duCjZOWWswL25lSHp4SXFjZ3draFEzUlZ1RnROUHFURFA4QkQwbDdhNkR5VzRZN1dPS2JHemUvWmFza2ZiSGoydnIKeVgzTGt1TTdzVW9KCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5603D6A5313073DDE9A88953C847BC8A.yl4.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
    user: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
  name: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
current-context: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:680688655542:cluster/Ahmad-EKS
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - Ahmad-EKS
      command: aws
      env:
      - name: AWS_PROFILE
        value: ahmad_personal
