apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  defaultBackend:
    service:
      name: test
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing  # This should match the selector in your Service
  template:
    metadata:
      labels:
        app: testing  # Labels for pod should match the selector
    spec:
      containers:
      - name: simple-web
        image: nginx:alpine
        ports:
        - containerPort: 80  # Port that the container exposes

---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: testing
  type: ClusterIP

