apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:

  # Helm chart source
  - repoURL: oci://public.ecr.aws/karpenter/karpenter
    chart: karpenter
    targetRevision: 1.9
    # createNamespace: true
    helm:
      valueFiles:
        - $values/apps/values/karpenter.yaml

  # Git repo source for values
  - repoURL: git@github.com:ahmadkaleem2/EKS-GitOps-Platform.git
    targetRevision: main
    ref: values
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-resources
  namespace: 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:ahmadkaleem2/EKS-GitOps-Platform.git
    targetRevision: main
    path: apps/additional-resources/karpenter
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true