apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi-hello-world  # Use .Release.Name to get the release name
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fastapi-hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi-hello-world
  template:
    metadata:
      labels:
        app: fastapi-hello-world
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
