# {{- if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
# {{- range $key, $value := .Values.ingress.annotations }}
#     {{ $key }}: {{ $value | quote }}
# {{- end }}
# spec:
#   ingressClassName: {{ .Values.ingress.ingressClass }}
#   rules:
#     - host: {{ .Values.ingress.host.fqdn }}
#       http:
#         paths:
# {{- range $path := .Values.ingress.host.paths }}
#           - path: {{ $path.path }}
#             pathType: {{ $path.pathType }}
#             backend:
#               service:
#                 name: {{ $.Release.Name }}-fastapi-hello-world-svc
#                 port:
#                   number: {{ $.Values.service.port }}
# {{- end }}
# {{- end }}







apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress

  annotations:
    alb.ingress.kubernetes.io/subnets: subnet-09642a6334b01c193, subnet-04ae5986180db2944
# {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: alb
  rules:
    - host: ahmad123456.ahmad.groveops.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-hello-world-svc
                port:
                  number: 80



# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress1
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx-example
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: fastapi-hello-world-fastapi-hello-world-svc
#             port:
#               number: 80


