
name: Terraform Apply or Destroy 
on:
  workflow_dispatch:
    inputs:
      apply_or_destroy:
        type: choice
        description: Whether to apply or destroy
        options: 
        - apply
        - destroy
        required: true
jobs:
  terraform:
    name: Terraform Apply or Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}  #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Initialize Terraform
        run: terraform init
      
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -var-file "./Environment/prod.tfvars" -out=tfplan
      
      - name: Apply or Destroy Terraform Configuration
        if: ${{ github.event.inputs.apply_or_destroy == 'apply' || github.event.inputs.apply_or_destroy == 'destroy' }}
        run: |
          if [ "${{ github.event.inputs.terraform }}" = "apply" ]; then
            terraform apply -auto-approve tfplan
          elif [ "${{ github.event.inputs.terraform }}" = "destroy" ]; then
            terraform destroy -auto-approve
          fi
