name: Maven Build and Push to JFrog

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}  # Replace with your Artifactory URL

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          maven-version: '3.6.3'
          distribution: 'temurin'

      - name: Get Last commit and build maven project with this tag
        run: |
          sed "s|\${revision}|${{ github.sha }}|" ./java_projects/spring-boot-tutorial-course/student-management-system/pom.xml > ./java_projects/spring-boot-tutorial-course/student-management-system/pom_temp.xml
          cd ./java_projects/spring-boot-tutorial-course/student-management-system/
          mvn clean install
          mvn -f ./pom_temp.xml package
      # - name: Publish to JFrog Artifactory
      #   env:
      #     USERNAME: ${{ secrets.username }}
      #     PASSWORD: ${{ secrets.password }}
      #   run: |
      #     curl -u $USERNAME:$PASSWORD -T ./java_projects/spring-boot-tutorial-course/student-management-system/target/student-management-system-${{ github.sha}}.jar "$ARTIFACTORY_URL/student-management-system-${{ github.sha}}.jar"
      
      
      - name: setup jfrog and push to Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
        env:
          JF_PROJECT: "student"
          JF_USER: ${{ secrets.username }}
          JF_PASSWORD: ${{ secrets.password }}
          JF_URL: ${{ secrets.ARTIFACTORY_URL}}

      - name: Push Build to Artifactory
        run: |

          export BUILD_NAME="student-management"
          # export BUILD_MODULE="my-module"
          export BUILD_NUMBER=${{ github.sha}}


          
          
          jf rt u "./java_projects/spring-boot-tutorial-course/student-management-system/target/student-management-system-${{ github.sha}}.jar" student/ 