name: Maven Build and Push to JFrog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          maven-version: '3.6.3'
          distribution: 'temurin'

      # - name: Get Last commit and build maven project with this tag
      #   run: |
      #     sed "s|\${revision}|${{ github.sha }}|" ./java_projects/spring-boot-tutorial-course/student-management-system/pom.xml > ./java_projects/spring-boot-tutorial-course/student-management-system/pom_temp.xml
      #     cd ./java_projects/spring-boot-tutorial-course/student-management-system/
      #     mvn clean install
      #     if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/release" ]]; then
      #       mvn -f ./pom_temp.xml package -P production
      #     else
      #       mvn -f ./pom_temp.xml package -P develop
      #     fi
      #     ls target
      # - name: Get Last commit and build maven project with this tag
      #   run: |
      #     echo "Creating build"
      #     cd ./java_projects/spring-boot-tutorial-course/student-management-system/
      #     if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/release" ]]; then
      #     mvn --no-transfer-progress external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-start -DallowSnapshots=true -DreleaseVersion="${{ inputs.version  }}" -DdevelopmentVersion="${{ inputs.version  }}-SNAPSHOT" -Dsquash=true -Doffline=true -DnoReleaseBuild=true -s .mvn/settings.xml
      #     mvn --no-transfer-progress external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish -Dsquash=true -DnoReleaseBuild=true -DkeepBranch=true -Doffline=true -DallowSnapshots=true -s .mvn/settings.xml -X
      #     git checkout release/${{ inputs.version  }}
      #     fi

      #     mvn clean package
      #     ls target
      - name: Setup JFrog CLI and Push to Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: '2.59.1'
        env:
        
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 
          
      - name: Push Build to Artifactory
        run: |
            # artifact_name=$(ls ./java_projects/spring-boot-tutorial-course/student-management-system/target/ | grep .jar$)
            echo $artifact_name
            jf rt u --access-token "${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}" --url "http://3.101.117.3:8081/artifactory" --flat "./java_projects/spring-boot-tutorial-course/student-management-system/pom.xml" "student/pom-${{ github.sha }}.xml"
            # jf rt u --flat "./java_projects/spring-boot-tutorial-course/student-management-system/target/$artifact_name" "student/student-${artifact_name}"


          # if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/release" ]]; then
          #   echo "publishing release"
          #   artifact_name=$(ls ./java_projects/spring-boot-tutorial-course/student-management-system/target/ | grep RELEASE.jar$)
          #   echo $artifact_name
          #   jf rt u --flat "./java_projects/spring-boot-tutorial-course/student-management-system/target/$artifact_name" "student/student-${artifact_name}"
          # else
          #   echo "publishing snapshot"
          #   artifact_name=$(ls ./java_projects/spring-boot-tutorial-course/student-management-system/target/ | grep SNAPSHOT.jar$)
          #   echo $artifact_name
          #   ls "./java_projects/spring-boot-tutorial-course/student-management-system/target/"
          #   ls "./java_projects/spring-boot-tutorial-course/student-management-system/target/$artifact_name"
          #   jf rt u --flat "./java_projects/spring-boot-tutorial-course/student-management-system/target/$artifact_name" "student/student-${artifact_name}"
          # fi
