name: Terraform Plan

on:
    pull_request:
      types:
        - opened  

concurrency: single

jobs:
  terraform:
    name: Terraform Plan
    if: github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }} # Change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: Initialize Terraform
        run: terraform init

      - name: Set Terraform Workspace
        run: terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Terraform Validate
        run: terraform validate

      - name: Plan or Apply or Destroy Terraform Configuration
        run: |
          if [ "${{ github.event.inputs.apply_or_destroy }}" = "apply" ]; then
            terraform apply -var-file "./Environment/${{ github.event.inputs.environment }}.tfvars" -auto-approve
          elif [ "${{ github.event.inputs.apply_or_destroy }}" = "destroy" ]; then
            terraform destroy -var-file "./Environment/${{ github.event.inputs.environment }}.tfvars" -auto-approve
          elif [ "${{ github.event.inputs.apply_or_destroy }}" = "plan" ]; then
            terraform plan -var-file "./Environment/${{ github.event.inputs.environment }}.tfvars"
          fi
