name: Terraform Apply or Destroy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      apply_or_destroy:
        type: choice
        description: Whether to apply or destroy
        options: 
        - apply
        - destroy

jobs:
  terraform:
    name: Terraform Apply or Destroy
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}  #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check -diff
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Apply or Destroy Terraform Configuration
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.apply_or_destroy }}" = "apply" ]; then
            terraform apply -auto-approve tfplan
          elif [ "${{ github.event.inputs.apply_or_destroy }}" = "destroy" ]; then
            terraform destroy -auto-approve
          fi
