name: Terraform plan

on:
  push:
    branches:
      - dev
jobs:
  terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}  #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        if: github.ref == 'refs/heads/dev'
        run: terraform plan -var-file "./Environment/prod.tfvars" -out=tfplan

      - name: Print Terraform Plan
        if: github.ref == 'refs/heads/dev'
        run: cat tfplan
